name: First Workflow
on:  workflow_dispatch
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: echo job
              run: echo "hello world"
            - name: another echo job
              run: echo "bello world"     